SELECT 
   TABLE_SCHEMA,
   TABLE_NAME,
   ORDINAL_POSITION
  ,COLUMN_NAME
  ,DATA_TYPE
  ,CHARACTER_MAXIMUM_LENGTH
  ,IS_NULLABLE
  ,COLUMN_DEFAULT

FROM   
  INFORMATION_SCHEMA.COLUMNS 
ORDER BY
  TABLE_NAME ASC; 